### ISSUE TITLE
board

### ISSUE THREAD

**Issue by zennieheo** [zennieheo/hackathon2024_BE#1]

**Comment by zennieheo** [comment]
# todo

1. 사진
- [x] 게시글에 업로드한 사진 잘 뜨도록
- [x] 사진 여러장 업로드 되도록

2. ??
- [x] 회원가입한 회원이 로그인 후 [ 게시글 작성, 수정, 삭제, 조회 ], [ 댓글 작성 ] 가능하도록 구현 --????
- [ ] 식단 추천에서 레시피 게시판으로 올 수 있도록....

3. api
- [x] api key authenticate 추가
- [x] username, password 입력칸 만들기

4. 배포
- [ ] gitignore에 추가 : venv, django etc.
- [ ] api 배포
